from __future__ import annotations
from typing import Protocol, List, Optional
from domain.models import Event, Participant


class EventRepo(Protocol):
    def load(self) -> Event: ...
    def save(self, event: Event) -> None: ...
    def add_participant(self, p: Participant) -> None: ...
    def remove_participant(self, participant_id: str) -> None: ...
    def list_participants(self, show_obsolete: bool = False) -> List[Participant]: ...
    def find_participant(self, participant_id: str) -> Optional[Participant]: ...
